version: "3.7"

services:
  db:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_DB: dot
      POSTGRES_USER: dot
      POSTGRES_PASSWORD: changeme
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  app:
    build:
      dockerfile: docker/java-ingest/Dockerfile
      context: .
    environment:
      - "spring.datasource.url=jdbc:postgresql://db:5432/dot"
      - "spring.datasource.username=dot"
      - "spring.datasource.password=changeme"
      - "spring.elasticsearch.rest.uris=elasticsearch:9200"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - elasticsearch
    volumes:
      - "./data:/app/data"
    restart: unless-stopped

volumes:
  db-data:
  es-data:

networks:
  default:
    name: osm2es
